train_data_path: artifacts/tokenized/*.pt
val_data_path: artifacts/tokenized/val_tokenized.jsonl
model_id: Qwen/Qwen2.5-Math-1.5B
device: cuda:0
vllm_device: cuda:1
vllm_gpu_memory_utilization: 0.85
microbatch_size: 2
num_epochs: 1
min_tokens_per_update: 4096
max_update_steps: null
learning_rate: 1e-5
adamw_beta1: 0.9
adamw_beta2: 0.95
adamw_eps: 1e-8
weight_decay: 0.0
max_grad_norm: 1.0
max_total_tokens: 2048
eval_every: 4
eval_examples: null
gen_max_new_tokens: 2048
gen_temperature: 0.0
gen_top_p: 1.0
checkpoint_dir: null
resume_from: null
