# @package traces
gen_traces:
  infile: artifacts/gsm8k/train.jsonl
  outfile: artifacts/deepseek_r1_gsm8k_traces.jsonl
  concurrency: 52
  max_tokens: 2048
  max_retries: 5
  samples_per_prompt: 1
  limit: 10

format_traces:
  infile: artifacts/deepseek_r1_gsm8k_traces.jsonl
  outfile: artifacts/r1_sft_pairs.jsonl
  limit: 10
