name: Build & Push (GHCR)

on:
  push:
    branches: [ main ]
    paths:
      - Dockerfile
      - .dockerignore
      - pyproject.toml
      - uv.lock
      - scripts/**
      - .github/workflows/build.yml
  workflow_dispatch:

permissions:
  contents: read
  packages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_REPO: grpo-gsm8k
    steps:
      - uses: actions/checkout@v4

      - name: Compute lowercase owner
        run: echo "OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

      - name: Set up Buildx (tiny local store, auto-cleanup)
        uses: docker/setup-buildx-action@v3
        with:
          cleanup: true
          buildkitd-flags: --oci-worker-gc=true --oci-worker-gc-keepstorage=1024

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ env.OWNER_LC }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ env.OWNER_LC }}/${{ env.IMAGE_REPO }}
          tags: |
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
            type=sha,prefix=sha-,format=short

      - name: Build & push (NO CACHE)
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          no-cache: true          # <- do not use/import any cache
          provenance: false
          sbom: false

      # Ensure nothing lingers on disk after build
      - name: Prune buildx + docker
        if: always()
        run: |
          docker buildx prune -af || true
          docker system prune -af || true
